import Head from "next/head";
import { ReactNode } from "react";
import Footer from "../footer/footer";
import Navbar from "../navbar/navbar";

const Layout = (props: { children: ReactNode }) => {
  return (
    <div style={{ display: "flex", flexFlow: "column", height: "100%" }}>
      <Head>
        <title>Solid Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      {props.children}
      <Footer />
    </div>
  );
};

export default Layout;
