import type { NextPage } from 'next'
import Head from 'next/head'
import { SessionProvider } from '@inrupt/solid-ui-react'

const Home: NextPage = () => {
  return (
    <div style={ { display: 'flex', flexFlow: 'column', height: '100%' } }> 
      
      <Head>
        <title>Solid Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SessionProvider sessionId='some-id'>
        
        <div style={ { flex: '0 1 auto' }}>

          <header style={{ 
            height: '70px',
            backgroundColor: "#9063CD",
            paddingTop: '5px',
            paddingBottom: '5px',
            margin: '5px 5px 0 5px',
            borderTopLeftRadius: '8px',
            borderTopRightRadius: '8px'
          }}>
          
            <div style={ { minWidth: '1000px', display: 'flex', paddingLeft: '100px' } }>
              <div style={ { fontSize: '30px', color: "#CBC3E3" }}>SOLID <span style={ { fontSize: '40px', fontWeight: 'bold', color: 'white' }}>Calendar</span></div>
            </div>
          </header>
          
          <div style={{
            height: '7px', 
            backgroundColor: "#CBC3E3",
            margin: '0px 5px 0 5px',
            borderBottomLeftRadius: '8px',
            borderBottomRightRadius: '8px'
          }}/>
        
        </div>

        <div style={ { 
          flex: '1 1 auto',
          display: 'grid', 
          gridTemplateColumns: '20% 60% 20%', 
          gridTemplateRows: '50px fit-content(100px) minMax(10px, 150px) auto auto 50px' }}>

          <div style={{
            gridColumnStart: 2,
            gridColumnEnd: 2,
            gridRowStart: 2,
            gridRowEnd: 2,
            backgroundColor: "#f7f9fb",
            borderRadius: '8px',
            boxShadow: 'rgba(0, 0, 0, 0.04) 0px 0px 5px 5px',
          }}>
          
            <div style={{ 
              backgroundColor: 'white',
              textAlign: 'center',
              fontWeight: 'bold',
              fontSize: '20px',
              color: "#9063CD",
              borderTopLeftRadius: '8px',
              borderTopRightRadius: '8px',
              paddingTop: '10px',
              paddingBottom: '10px'
            }}>
              Where is your Pod hosted?
            </div>

            <div style={{
              display: 'flex',
              flexFlow: 'row',
            }}>
            </div>

          </div>

          <div style={ { 
            gridColumnStart: 2,
            gridColumnEnd: 2,
            gridRowStart: 4,
            gridRowEnd: 4,
            backgroundColor: "#f7f9fb",
            borderRadius: '8px',
            boxShadow: 'rgba(0, 0, 0, 0.04) 0px 0px 10px 5px',
          }}>
            
            <div style={{ 
              backgroundColor: 'white',
              textAlign: 'center',
              fontWeight: 'bold',
              fontSize: '20px',
              color: "#9063CD",
              borderTopLeftRadius: '8px',
              borderTopRightRadius: '8px',
              paddingTop: '10px',
              paddingBottom: '10px'
            }}>
              How to start using SOLID Calendar?
            </div>
          
          </div>

        </div>

        <div style={{ 
          flex: '0 1 40px',
          backgroundColor: "#f7f9fb",
          margin: '5px 5px 5px 5px',
          borderTopLeftRadius: '8px',
          borderTopRightRadius: '8px'
        }}>
          
        </div>

      </SessionProvider>
    </div>
  )
}

export default Home
